Separate the processing of the QuicException and Http3Exception error…
netty/netty-incubator-codec-http3 pull request #166
Opened 2021-09-08 17:18 UTC by abezhovets

**Motivation**

Change the `Http3RequestStreamInboundHandler` such that by default it does not propagate the `QuicException` and `Http3Exception` to the pipeline further and reduce noisy logs.

**Modification**

Separate the processing of these errors into separate methods and simply log by default.

**Result**

Fixes #164

2021-09-08 18:56 UTC, NiteshKant requested changes
Thanks a lot @abezhovets, few minor comments and then looks good.

2021-09-08 18:56 UTC, NiteshKant commented on src/main/java/io/netty/incubator/codec/http3/Http3RequestStreamInboundHandler.java
> +     * @param frame         the {@link Http3DataFrame} that caused the error.
Is this intentional? If not, please revert

2021-09-08 18:56 UTC, NiteshKant commented on src/main/java/io/netty/incubator/codec/http3/Http3RequestStreamInboundHandler.java
> +
nit: remove the empty line.

2021-09-08 18:56 UTC, NiteshKant commented on src/main/java/io/netty/incubator/codec/http3/Http3RequestStreamInboundHandler.java
> +     * Called once a {@link QuicException} should be handled. By default, these exceptions are just logged
nit: Committing to implementation details in the API are not generally recommended as we may change it later but some folks may depend on the behavior.

```suggestion
     * Handles a {@link QuicException} raised via {@link ChannelPipeline#exceptionCaught(ChannelHandlerContext,  Throwable)}.
```

2021-09-08 18:56 UTC, NiteshKant commented on src/main/java/io/netty/incubator/codec/http3/Http3RequestStreamInboundHandler.java
> +        logger.error("Caught QuicException.", exception);
Since the pipeline appropriately handles `QuicException` and no user action is typically required, we can log at `DEBUG` level here.

2021-09-08 20:50 UTC, NiteshKant commented
@abezhovets the build failed due to check style failures. If you run `./mvnw compile` locally you can see the check style failures.

2021-09-08 20:51 UTC, NiteshKant commented on src/main/java/io/netty/incubator/codec/http3/Http3RequestStreamInboundHandler.java
> +        logger.error("Caught QuicException.", exception);
Also can you add the channel to the log message here? It will help debugging.

2021-09-13 11:16 UTC, normanmaurer approved these changes

2021-09-13 22:22 UTC, NiteshKant approved these changes

2021-09-13 23:19 UTC, merged