Apply Nullable/NotNullByDefault annotations
netty/netty-incubator-codec-http3 pull request #289
Opened 2024-03-01 17:36 UTC by simonatan

Motivation:
`Nullable`/`NotNullByDefault` annotations give an idea of what to expect from the API. Plus, they provide a better IDE integration. This PR is based on the work done in netty/netty#12878

Modification:
`Nullable`/`NotNullByDefault` annotations are applied where necessary.

Result:
The change extends the API with nullability expectations. Plus, it provides a better IDE integration.

2024-03-01 20:07 UTC, normanmaurer requested changes

2024-03-02 12:54 UTC, simonatan commented on src/main/java/io/netty/incubator/codec/http3/internal/NotNullByDefault.java
> +public @interface NotNullByDefault {
Okay, I moved it to the upper package.

2024-03-12 13:59 UTC, simonatan commented
@normanmaurer PTAL

2024-03-27 09:59 UTC, normanmaurer approved these changes

2024-03-28 12:37 UTC, merged

2024-03-28 12:37 UTC, normanmaurer commented
@simonatan thanks